### 1. Testar se a API está online
GET http://localhost:3006/
Accept: application/json

###

### 2. Cadastrar o Produto Único
POST http://localhost:3006/produto
Content-Type: application/json

{
  "nome": "Belle Spray",
  "preco": 60.00,
  "descricao": "Spray para espinhas.",
  "estoque": 45
}

###

### 3. Cadastrar um Cliente
POST http://localhost:3006/clientes
Content-Type: application/json

{
  "nome": "Fernando",
  "telefone": "13 997097821",
  "cpf": "123.456.789.00",
  "email": "feranndo10@gmail.com",
  "senha": "senha_segura"
}

###

### 4. Cadastrar um Cupom de Desconto
POST http://localhost:3006/cupons
Content-Type: application/json

{
  "codigo": "BELLEVISAGE10",
  "desconto": 20.00,
  "validade": "2026-07-05"
}

###

### 5. Buscar o Cupom pelo Código
GET http://localhost:3006/cupons/DESCONTO10
Accept: application/json

###

### 6. Criar um Pedido
POST http://localhost:3006/pedidos
Content-Type: application/json

{
  "cliente_id": 1,
  "data_pedido": 2026-05-30,
  "pagamento_id": 1,
  "status_pedido": "Pendente",
  "subtotal": 60.00,
  "frete": 20.00,
  "cupom_id": 1
}

###

### 7. Listar todos os Pedidos criados
GET http://localhost:3006/pedidos
Accept: application/json